In [3]:
import numpy as np

In [14]:
np.random.seed(4)
height=np.random.randint(10,50,30)
age=np.random.randint(18,40,30)

In [15]:
age

array([34, 35, 27, 34, 30, 36, 21, 29, 36, 24, 25, 31, 28, 25, 27, 36, 39,
       37, 34, 39, 33, 22, 29, 37, 26, 23, 26, 25, 18, 22])

In [16]:
height

array([15, 11, 33, 18, 19, 49, 40, 46, 48, 13, 10, 31, 31, 19, 48, 48, 12,
       40, 18, 12, 33, 42, 43, 42, 38, 13, 25, 44, 41, 27])

In [17]:
"heigth is dependent on age"

'heigth is dependent on age'

In [18]:
age=age.reshape(-1,1)

In [20]:
from sklearn.linear_model import LinearRegression

In [22]:
linear= LinearRegression()

In [23]:
linear.fit(age,height)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
linear.predict([[20]])

array([31.92080378])

In [31]:
linear.coef_

array([-0.16883373])

In [32]:
linear.intercept_

35.29747832939323

In [36]:
"list out the regression metrics in ml"

'list out the regression metrics in ml'

In [1]:
from sklearn.neighbors import KNeighborsClassifier

In [2]:
m=KNeighborsClassifier()

In [3]:
m

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [6]:
a=np.random.randint(20,100,20)

In [28]:
import numpy as np
import pandas as pd

In [8]:
a[a>70]

array([96, 89, 96, 79, 74])

In [11]:
a=pd.read_csv("train.csv")

In [17]:
b=a["Age"]

In [18]:
b=b.fillna(method="ffill")

In [19]:
b=b.values

In [31]:
b.isna()

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

In [38]:
c=a["Survived"].values

In [41]:
m.fit(b,c)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [40]:
b=b.reshape(-1,1)

In [52]:
m.predict([[29]])

array([0], dtype=int64)

In [48]:
m.score(b,c)

0.6083052749719416

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [58]:
a["Age"]==np.NaN
    

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
861    False
862    False
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [1]:
"data base"

'data base'

In [30]:
import pandas as pd

In [31]:
df=pd.read_csv("train.csv")

In [32]:
x=df.loc[:,["Age","Fare"]]

In [33]:
y=df["Survived"]

In [34]:
x.isna().sum()

Age     177
Fare      0
dtype: int64

In [35]:
x["Age"].fillna(method="bfill",inplace=True)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
a=KNeighborsClassifier()

In [21]:
b=np.random.randint(30,70,50)

In [22]:
c=np.random.randint(10,20,50)

In [39]:
x1,x2,y1,y2=train_test_split(x,y,test_size=0.30)

In [44]:
x1

Age      Fare
406  51.00    7.7500
476  34.00   21.0000
452  30.00   27.7500
129  45.00    6.9750
525  40.50    7.7500
353  25.00   17.8000
852   9.00   15.2458
341  24.00  263.0000
516  34.00   10.5000
868   4.00    9.5000
800  34.00   13.0000
537  30.00  106.4250
640  20.00    7.8542
850   4.00   31.2750
636  32.00    7.9250
644   0.75   19.2583
139  24.00   79.2000
739  36.00    7.8958
630  80.00   30.0000
291  19.00   91.0792
564  24.00    8.0500
499  24.00    7.7958
384  18.00    7.8958
42    3.00    7.8958
888  26.00   23.4500
881  33.00    7.8958
196  42.00    7.7500
319  40.00  134.5000
697  49.00    7.7333
393  23.00  113.2750
..     ...       ...
200  28.00    9.5000
474  22.00    9.8375
885  39.00   29.1250
695  52.00   13.5000
195  58.00  146.5208
240  29.00   14.4542
623  21.00    7.8542
295  23.50   27.7208
611  35.00    7.0500
570  62.00   10.5000
661  40.00    7.2250
461  34.00    8.0500
70   32.00   10.5000
675  18.00    7.7750
184   4.00   22.0250
584  18.00    8.7125
507  28.00   26.5500
751   6.00   12.4750
122  32.50   30.0708
828  62.00    7.7500
827   1.00   37.0042
436  21.00   34.3750
693  25.00    7.2250
399  28.00   12.6500
513  54.00   59.4000
498  25.00  151.5500
199  24.00   13.0000
227  20.50    7.2500
763  36.00  120.0000
837  32.00    8.0500

[623 rows x 2 columns]

In [25]:
x2.shape

(15,)

In [41]:
y1.shape

(623,)

In [42]:
y2.shape

(268,)

In [45]:
a.fit(x1,y1)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [46]:
a.score(x1,y1) #training accuracy

0.7752808988764045

In [47]:
a.score(x2,y2) #testing acuracy

0.6567164179104478

In [51]:
train=[]
test=[]
for i in range(10):
    x1,x2,y1,y2=train_test_split(x,y
                                 ,test_size=0.30
                                 ,random_state=i)
    a.fit(x1,y1)
    train.append((a.score(x1,y1)))
    test.append((a.score(x2,y2)))
    

In [52]:
sum(train)/len(train)

0.7597110754414126

In [53]:
len(train)

10

In [55]:
sum(test)/len(test)

0.6511194029850745

In [50]:
b=pd.read_csv("phones_data.csv")

In [69]:
b.isna().sum()

Unnamed: 0        0
brand_name        0
model_name        0
os                0
popularity        0
best_price        0
lowest_price      0
highest_price     0
sellers_amount    0
screen_size       2
memory_size       0
battery_size      0
release_date      0
dtype: int64

In [52]:
b["os"].fillna(method="ffill",inplace=True)

In [53]:
b["lowest_price"].fillna(method="bfill",inplace=True)

In [54]:
b["memory_size"].fillna(method="ffill",inplace=True)

In [55]:
b["highest_price"].fillna(method="bfill",inplace=True)

In [56]:
b["battery_size"].fillna(method="bfill",inplace=True)

In [70]:
x=b.loc[:,["highest_price","battery_size"]]

In [77]:
y=b.loc[:,"brand_name"]

In [72]:
x1,x2,y1,y2=train_test_split(x,y,test_size=0.30)

In [73]:
b["battery_size"].shape

(1224,)

In [82]:
linear=LinearRegression
a.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [83]:
a.score(x1,y1)

0.6156542056074766

In [99]:
x=np.random.randint(10,50,30)

In [100]:
y=np.random.randint(40,100,30)

In [106]:
inte=((y.sum())*((x**2).sum())-((x.sum())*((x*y).sum())))/len(x**2)

In [102]:
y*2

array([150, 166, 186,  94,  82, 170,  84, 194,  96, 116, 186, 138, 108,
       140, 148, 188,  98, 164, 118, 110, 154, 176, 112, 100,  84, 196,
       176, 182, 102, 160])

In [104]:
y.sum()

2089

In [107]:
len(y)

30

## k fold crossvalidation

In [110]:
"1-all sample train and text","this is not good"

('1-all sample train and text', 'this is not good')

In [109]:
"2 split into train and test" "not the best"

'2 split into train and test'

In [111]:
"divide then use dem to test and train individuually"

'divide then use dem to test and train individuually'

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
data=load_digits()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
x1,x2,y1,y2=train_test_split(data.data,data.target,test_size=0.3)

In [5]:
x1

array([[ 0.,  1., 10., ...,  5.,  0.,  0.],
       [ 0.,  0.,  0., ..., 13.,  7.,  0.],
       [ 0.,  0.,  4., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  2.,  0.,  0.],
       [ 0.,  0.,  0., ..., 13.,  3.,  0.],
       [ 0.,  0.,  3., ...,  0.,  0.,  0.]])

In [6]:
ab=LogisticRegression(multi_class="auto")
ab.fit(x1,y1)
ab.score(x2,y2)

C:\Users\HP PC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9574074074074074

In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [10]:
for train,text in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train,text)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def fun(model,x1,x2,y1,y2):
    model.fit(x1,y1)
    return model.score(x2,y2)

In [12]:
fun(kf,x1,x2,y1,y2)

AttributeError: 'KFold' object has no attribute 'fit'

In [13]:
y1

array([3, 1, 7, ..., 4, 2, 1])

In [14]:
x2

array([[ 0.,  1.,  5., ...,  5.,  0.,  0.],
       [ 0.,  0.,  3., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 13., 12.,  2.],
       ...,
       [ 0.,  0., 10., ...,  8.,  1.,  0.],
       [ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  4., ...,  8.,  0.,  0.]])

In [15]:
from sklearn.model_selection import StratifiedKFold

In [16]:
folds=StratifiedKFold(n_splits=3)

In [19]:
score1=[]
scores=[]
ss=[]
for train,test in kf.split(data.data):
    x1,x2,y1,y2=data.data[train],data.data[test],data.target[train],data.target[test]
    

[[ 0.  0.  1. ... 16. 16.  8.]
 [ 0.  0. 10. ... 16. 16.  9.]
 [ 0.  0.  6. ... 16. 15.  3.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  1. 13. ...  0.  0.  0.]
 [ 0.  1.  7. ... 12.  2.  0.]
 [ 0.  0. 13. ...  0.  0.  0.]]


In [18]:
x1

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  1., 13., ...,  0.,  0.,  0.],
       [ 0.,  1.,  7., ..., 12.,  2.,  0.],
       [ 0.,  0., 13., ...,  0.,  0.,  0.]])

## machine learning

In [20]:
"linear regression"

'linear regression'

In [1]:
x=[1,2,3,4,5,6,7,8]
y=[3,4,5,6,7,8,9,2]
xy=[]
x_s=[]
for a,b in zip(x,y):
    xy.append(a*b)

In [11]:
x=x.reshape(-1,1)

In [3]:
import numpy as np

In [4]:
x=np.linspace(2,10,30)

In [6]:
y=3+2*x

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
linear=LinearRegression()

In [12]:
linear.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
linear.intercept_

3.000000000000007

logistic regression ia for classification

cats and dog example

## one hot encoding

In [1]:
import pandas as pd
dd=pd.read_csv("insurance.csv")

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
data=pd.read_csv("insurance.csv",usecols=["sex","smoker","region"])

In [29]:
for  i in data.columns:
    print(i,':',len(data[i].unique()))

sex : 2
smoker : 2
region : 4


In [31]:
pd.get_dummies(data,drop_first=True).shape

(1338, 5)

In [32]:
data.shape

(1338, 3)